import type {
  AppSettings,
  FileQueueItem,
  TranscriptResult,
} from "../types/domain";
export const settingsFixture: AppSettings = {
  defaultMode: "quick_dictate",
  shortcut: "CmdOrCtrl+Shift+Space",
  shortcutMode: "push_to_talk",
  languageMode: "auto",
  fixedLanguage: null,
  preferredInputDevice: null,
  insertBehavior: "paste",
  launchAtLoginEnabled: false,
  gpuEnabled: true,
  shortcutDictationModelProfile: "balanced",
  shortcutDictationSelectedModelId: null,
  quickDictateModelProfile: "balanced",
  quickDictateSelectedModelId: null,
  fileTranscribeModelProfile: "balanced",
  fileTranscribeSelectedModelId: null,
  appearance: "system",
  motionPreference: "system",
  soundsEnabled: true,
  saveHistory: true,
  volumeDuckingEnabled: true,
  fileDiarizationEnabled: false,
};
export const resultFixture: TranscriptResult = {
  jobId: "result-1",
  modelName: "whisper",
  fullText: "A useful thought.",
  plainText: "A useful thought.",
  timestampedText: "A useful thought.",
  detectedLanguages: ["en"],
  segments: [],
  speakers: [],
  diarizationTurns: [],
  qualityStatus: "clean",
  recoveredRegionCount: 0,
  warnings: [],
  diarizationStatus: "not_requested",
  diarizationModelId: null,
  diarizationWarning: null,
  diarizationPolicyVersion: null,
  diarizationClusteringThreshold: null,
  diarizationSpeakerCountHint: null,
};
export const fileFixture: FileQueueItem = {
  id: "file-1",
  sourceFile: {
    filePath: "/recordings/meeting.wav",
    originalName: "meeting.wav",
    mimeType: "audio/wav",
    sha256: null,
    sizeBytes: 1048576,
    durationMs: 60000,
  },
  stage: "transcribing",
  progressPercent: null,
  processedMs: null,
  totalMs: null,
  etaSeconds: null,
  statusText: "Transcribing on your device.",
  result: null,
  errorMessage: null,
  startedAt: 1,
  isExpanded: false,
  copyState: "idle",
};
